### ISSUE TITLE
NullPointerException in JRE 8 Font

### ISSUE THREAD

**Issue by joelchen** [docker-library/java#46] opened 2015-07-02 11:58 UTC
This [StackOverflow][1] question and answer describes the issue. It only happens
 in JRE 8 but not in JRE 7.

[1]: http://stackoverflow.com/questions/30626136/cannot-load-font-in-jre-8

**Comment by yosifkit** [comment] 2015-07-02 16:46
I am not sure we would want to change away from the `-headless` packages.  Why not just use the jdk versions, or extend the jre image in your Dockerfile and install the non-headless package?

**Comment by md5** [comment] 2015-07-02 17:14
I'd like to see a test case to reproduce this. It sounds like the JRE is not running actually in headless mode.

**Comment by md5** [comment] 2015-07-03 04:47
I was able to reproduce this: https://gist.github.com/md5/7fb07efafee3802da457

It looks like installing `libfontconfig1` is a workaround (see the gist).

**Comment by yosifkit** [comment] 2015-07-06 19:08
@md5, what do you suggest? Do you think we should add `libfontconfig1` to the jre image or should we just point out that a user may need to add libs like this to their images?

**Comment by tianon** [comment] 2015-07-06 20:01
Alternatively, could this be considered a missing dependency on the Debian
package, or is this strictly something users are supposed to be able to
handle from their PoV?

**Comment by md5** [comment] 2015-07-06 20:48
I think what @tianon said is correct. This seems to be a missing dependency that should be fixed at the Debian level. I don't have time at the moment to investigate why this may have changed between `openjdk-7-jre-headless` and `openjdk-8-jre-headless` or to report it to `debian-java@lists.debian.org`, but I think that's what needs to happen.

The problem I see with simply adding `libfontconfig1` is that without determining the root cause of why it's no longer being installed, it's quite likely that there could be other missing libraries that we don't know about yet that are waiting to crop up. Still, if it's enough of an issue for enough people, adding the `libfontconfig1` package seems like a pretty unobtrusive move.

My suspicion is that something moved from a dependency to a "recommends", resulting in a bunch of packages being dropped. I'm also wondering whether something might have happened during the Jessie backport process to mess up the dependencies.

**Comment by yosifkit** [comment] 2015-07-06 23:28
As far as I can tell, this is a packaging issue. Here are the depends that get `libfontconfig1` for java 7 and 8:
```console
openjdk-7-jre-headless -> libfontconfig1
# it is a direct dependency

openjdk-7-jre -> libfontconfig1
# also has longer paths to require libfontconfig1

openjdk-8-jre-headless -> # no fontconfig

openjdk-8-jre -> libatk-wrapper-java-jni -> libcairo2 -> libfontconfig1
# the shortest path to require it
```

**Comment by joelchen** [comment] 2015-07-22 14:21
I have just filed a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793210) with Debian.

**Comment by md5** [comment] 2015-07-23 17:23
Thanks @joelchen! :+1:

**Comment by md5** [comment] 2015-08-20 17:07
@tianon @yosifkit What do you guys think of putting in a temporary fix for this, since there doesn't seem to be much movement on the Debian front.

I just got an error report for the `jetty` image for this same issue: appropriate/docker-jetty#15.

**Comment by yosifkit** [comment] 2015-08-20 17:27
Sounds fine to me.

**Comment by tianon** [comment] 2015-08-20 19:59
@md5 totally throwing that in now unless you beat me to it :wink:

**Closed** 2015-08-20 20:12 UTC

**Comment by md5** [comment] 2015-08-20 20:26
@tianon I was thinking about creating a PR when I got back from lunch, but there's no need now. Thanks.

**Comment by tianon** [comment] 2015-08-20 20:41
Sorry, I got a little antsy. :innocent:

**Comment by joelchen** [comment] 2015-08-21 06:16
Thanks @md5, @tianon, and @yosifkit! 👍
